# Generated by Django 4.0 on 2021-12-21 09:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('eid', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phno', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Location', models.CharField(max_length=50)),
            ],
        ),
    ]
